// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW7mI9x0RIzTnLRKyIDwo8Mwl1Xtp82n4',
    appId: '1:782601360703:web:04a7d7bcaeb49c2be4af8a',
    messagingSenderId: '782601360703',
    projectId: 'auth-router-context-36be7',
    authDomain: 'auth-router-context-36be7.firebaseapp.com',
    storageBucket: 'auth-router-context-36be7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwyXAbtPFkoVzb0bA33eiI28vc12GbHVc',
    appId: '1:782601360703:android:bb5bcb7acea09dd1e4af8a',
    messagingSenderId: '782601360703',
    projectId: 'auth-router-context-36be7',
    storageBucket: 'auth-router-context-36be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hSRKBY3NRNpiBu1zApEaDZWIg__khoc',
    appId: '1:782601360703:ios:3a93ca95934361cce4af8a',
    messagingSenderId: '782601360703',
    projectId: 'auth-router-context-36be7',
    storageBucket: 'auth-router-context-36be7.firebasestorage.app',
    iosClientId: '782601360703-ch1268esjhkr900m5epndn6n9asiol01.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessaging',
  );
}
