permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to build from"
        required: true
        default: "main"

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }} # Uses your manual input

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"
          channel: "stable"

      - run: flutter build apk --release
      - run: flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/app.ipa
          tag: v1.0.5-main
          token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true
          replacesArtifacts: true
          makeLatest: true
